services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

  valkey:
    image: valkey/valkey

  vector_db:
    image: qdrant/qdrant:latest
    container_name: vector_db
    ports:
      - "6333:6333"  
